import { Question, Topic, Unit } from './types';
import { lessons } from './lessons';
export const units = [
 { id: 1, title: 'Fundamentos da inovação', subtitle: 'Das ideias à transformação', color: '#7255bd' },
 { id: 2, title: 'Estratégia e diferenciação', subtitle: 'Novos caminhos para competir', color: '#168577' },
 { id: 3, title: 'Gestão e difusão', subtitle: 'Planejar, medir e transformar', color: '#b77824' },
 { id: 4, title: 'Recursos e competências', subtitle: 'Construindo vantagens duradouras', color: '#407fb5' },
] as const;
// Base editorial do MVP. Não substitui a apostila. Cada entrada tem proveniência explícita.
// [unidade, título, conceito, exemplo, pergunta, correta, distratores...]
const rows: [Unit, string, string, string, string, string, string, string, string][] = [
 [1,'Conceito de inovação','Inovação exige implementação de uma novidade ou melhoria relevante. Uma ideia, isoladamente, não é inovação.','Um restaurante testa e implanta um novo sistema de reposição que reduz sobras.','O que transforma uma ideia em inovação?','Sua implementação em uso ou no mercado','Apenas a criatividade de quem a propôs','Seu registro em uma lista de sugestões','A intenção de investir no futuro'],
 [1,'Stoeckicht','Na abordagem estudada, inovar envolve transformar conhecimento e ideias em valor. A formulação literal da autora depende da consulta à apostila.','Uma sugestão da equipe se torna uma rotina aplicada e avaliada.','Qual situação melhor representa a transformação de ideias em valor?','Implantar e avaliar uma solução para um problema real','Acumular sugestões sem aplicá-las','Confundir originalidade com resultado comprovado','Considerar qualquer reunião uma inovação'],
 [1,'IBGE e inovação','A inovação de produto ou processo exige novidade ou melhoria significativa para a empresa e implementação. Não precisa ser inédita no mundo.','Uma empresa passa a usar um processo significativamente melhor, já usado em outro setor.','Uma inovação precisa ser inédita mundialmente?','Não; pode ser nova para a empresa, atendidos os critérios de implementação','Sim; novidade mundial é sempre obrigatória','Não; basta imaginar uma mudança','Sim; só invenções patenteadas contam'],
 [1,'Porter e inovação','A inovação pode contribuir para vantagem competitiva ao alterar produtos, processos ou formas de competir. Não se limita a alta tecnologia.','Uma operação organiza pedidos de maneira mais eficiente e oferece melhor prazo.','Como a inovação pode favorecer a competição?','Criando valor ou melhorando a forma de executar atividades','Garantindo lucro automaticamente','Eliminando toda concorrência para sempre','Exigindo sempre tecnologia inédita'],
 [1,'Schumpeter: novas combinações','As novas combinações incluem novos produtos, métodos de produção, mercados, fontes de suprimento e formas de organização.','Uma empresa explora um mercado antes não atendido.','Qual alternativa integra as novas combinações de Schumpeter?','Abertura de um novo mercado','Repetição obrigatória dos mesmos métodos','Proibição de novas fontes de fornecimento','Manutenção inalterada da organização'],
 [1,'4 Ps da inovação','Os 4 Ps são produto, processo, posição e paradigma. Posição muda o contexto de oferta; paradigma muda a lógica mental do negócio.','Um serviço tradicional passa a atender um público diferente: mudança de posição.','Qual conjunto corresponde aos 4 Ps da inovação?','Produto, processo, posição e paradigma','Preço, praça, promoção e produto','Pessoas, prazo, preço e produção','Pesquisa, patente, preço e propaganda'],
 [1,'Technology push','Technology push parte de avanços científicos e tecnológicos que impulsionam aplicações e ofertas.','Uma nova técnica de conservação permite desenvolver outro produto.','No technology push, qual é o impulso predominante?','O avanço científico e tecnológico','A demanda explicitada pelo consumidor como único ponto de partida','A imitação sem desenvolvimento','A eliminação de pesquisa'],
 [1,'Demand pull','Demand pull enfatiza necessidades do mercado como estímulo ao desenvolvimento de soluções.','Clientes pedem refeições com entrega rápida e a empresa desenvolve uma oferta.','Uma solução desenvolvida em resposta a uma necessidade de mercado exemplifica:','Demand pull','Technology push como origem exclusiva','Ausência de inovação','Pesquisa sem relação com demanda'],
 [1,'Gerações de inovação','Os modelos evoluem de explicações lineares para acoplamento, integração e redes. A numeração e a inclusão de uma sexta geração variam conforme a referência.','Pesquisa, produção e fornecedores colaboram em vez de apenas passar tarefas adiante.','Qual tendência caracteriza a evolução dos modelos de inovação?','Maior integração e interação entre participantes','Isolamento crescente e obrigatório da pesquisa','Eliminação de toda retroalimentação','Substituição de toda colaboração por sequência rígida'],
 [1,'Chain-link','O modelo chain-link articula mercado, projeto, produção e conhecimento por interações e feedbacks. A pesquisa pode ser acionada em diferentes etapas.','Uma falha na produção leva a rever o projeto e consultar conhecimento científico.','Qual é uma característica central do chain-link?','Interações e retroalimentações entre etapas e conhecimento','Pesquisa conectada à empresa em uma única etapa','Fluxo obrigatório sem retorno','Mercado sempre separado do desenvolvimento'],
 [1,'Ciência e tecnologia','Ciência busca produzir conhecimento; tecnologia mobiliza conhecimentos, técnicas e métodos para finalidades práticas. Inovação exige aplicação de novidade relevante.','Conhecimento sobre calor fundamenta um equipamento de cocção.','Qual distinção é adequada?','Ciência produz conhecimento e tecnologia o articula para aplicações práticas','Ciência e tecnologia são sempre sinônimos','Tecnologia se restringe a computadores','Toda descoberta científica já é inovação comercial'],
 [1,'Destruição criativa','Em Schumpeter, novas combinações transformam a economia, substituindo ou reconfigurando produtos, negócios e estruturas anteriores.','Um novo formato de serviço modifica a demanda por modelos tradicionais.','O que significa destruição criativa?','Transformação de estruturas econômicas por inovações','Destruir equipamentos sem gerar valor','Manter mercados estáticos','Impedir o surgimento de novos empreendedores'],
 [1,'Teoria evolucionista','A perspectiva evolucionista enfatiza variedade, seleção, aprendizagem e mudança de rotinas ao longo do tempo. Não pressupõe adaptação garantida.','Empresas testam rotinas; algumas se difundem, outras são abandonadas.','Qual ideia combina com a perspectiva evolucionista?','Aprendizagem e seleção de rotinas em ambientes mutáveis','Todas as empresas se adaptam com sucesso garantido','Mercados permanecem sempre em equilíbrio imutável','Não há diversidade de comportamentos empresariais'],
 [2,'Inovação de produto','Refere-se à introdução de bens ou serviços novos ou significativamente melhorados.','Um restaurante oferece uma nova linha de refeições com características distintas.','Uma nova oferta com características significativamente melhoradas é inovação de:','Produto','Processo exclusivamente','Organização exclusivamente','Marketing exclusivamente'],
 [2,'Inovação de processo','Muda significativamente a maneira de produzir ou entregar bens e serviços.','Uma nova rotina e equipamento alteram a montagem e entrega dos pedidos.','Uma melhoria significativa no método de produção é inovação de:','Processo','Produto obrigatoriamente','Posicionamento exclusivamente','Marca exclusivamente'],
 [2,'Inovação incremental','Envolve aperfeiçoamentos graduais de produtos ou processos existentes.','A equipe melhora progressivamente o porcionamento e o fluxo de trabalho.','O que caracteriza a inovação incremental?','Aperfeiçoamentos graduais de algo existente','Ruptura completa obrigatória','Ausência de implementação','Criação obrigatória de um mercado inédito'],
 [2,'Inovação radical','Envolve ruptura significativa em relação às soluções ou trajetórias anteriores. Seu grau depende do contexto e da referência.','Uma solução muda profundamente a forma de oferecer um serviço.','Qual situação melhor representa inovação radical?','Uma ruptura significativa com a solução anterior','Um ajuste rotineiro sem mudança relevante','Uma correção de digitação','Uma repetição exata do processo atual'],
 [2,'Marketing e organização','Na classificação tradicional estudada, marketing trata de novos métodos de comercialização; organizacional, de práticas, estrutura e relações de trabalho.','A empresa muda a forma de promover a oferta e reorganiza equipes.','Reformular significativamente as práticas de trabalho caracteriza principalmente inovação:','Organizacional','De produto necessariamente','De matéria-prima exclusivamente','De marketing obrigatoriamente'],
 [2,'Modelos de gestão e negócio','Modelo de gestão trata de como se coordena a organização; modelo de negócio explica como ela cria, entrega e captura valor.','Um restaurante adota assinatura de refeições em vez de vendas avulsas.','Passar a oferecer assinatura de refeições altera principalmente:','O modelo de negócio','Apenas a cor da embalagem','Somente a técnica de cocção','Necessariamente a legislação'],
 [2,'Inovação aberta','Combina conhecimentos e ideias internos e externos. Não é terceirização integral e não exige ser sempre o primeiro a chegar ao mercado.','Equipe, universidade e fornecedor desenvolvem uma solução juntos.','Qual afirmação é compatível com inovação aberta?','Conhecimentos internos e externos podem ser combinados','Somente ideias externas são aceitas','Toda pesquisa deve permanecer isolada','Ser o primeiro no mercado é sempre mais importante que o modelo de negócio'],
 [2,'Inovação fechada','Prioriza desenvolvimento e controle internos do processo de inovação, com fronteiras organizacionais mais restritas.','Uma empresa desenvolve sua solução em laboratório próprio e restringe o compartilhamento.','Qual traço caracteriza a inovação fechada?','Desenvolvimento e controle predominantemente internos','Funil permeável como princípio central','Uso exclusivo de ideias externas','Colaboração externa irrestrita como regra'],
 [2,'Benchmarking','Compara práticas e desempenhos para aprender e adaptar melhorias ao contexto. Não é copiar indiscriminadamente.','Uma cozinha analisa o fluxo de outra operação e adapta o aprendizado ao seu espaço.','Como usar benchmarking de forma adequada?','Comparar, aprender e adaptar ao contexto','Copiar tudo sem avaliar restrições','Comparar apenas logotipos','Ignorar diferenças entre operações'],
 [2,'Estratégias de Porter','As estratégias genéricas incluem liderança em custos, diferenciação e enfoque. Enfoque atende um segmento definido.','Uma empresa concentra sua oferta em um nicho com necessidades específicas.','Atender um segmento delimitado caracteriza a estratégia de:','Enfoque','Liderança em custos obrigatoriamente','Diversificação irrestrita','Ausência de estratégia'],
 [2,'Liderança em custos','Busca uma posição de custos relativos baixos, com eficiência ao longo das atividades. Preço baixo isolado não comprova essa estratégia.','Padronização e menor desperdício reduzem o custo por refeição sem comprometer o serviço.','O que sustenta liderança em custos?','Eficiência e estrutura de custos relativa favorável','Cobrar barato independentemente dos custos','Reduzir qualidade sem avaliar consequências','Vender com prejuízo como regra'],
 [2,'Diferenciação','Oferece atributos percebidos e valorizados como distintos pelo cliente. O valor percebido precisa justificar os custos da diferenciação.','Um serviço oferece conveniência e experiência que seu público valoriza.','Quando a diferenciação faz sentido estratégico?','Quando os atributos distintos são valorizados pelo público','Quando toda diferença gera valor automaticamente','Quando aumenta custos sem percepção de benefício','Quando ignora necessidades do cliente'],
 [2,'Oceano Azul','Busca criar espaços de mercado e inovação de valor. A matriz propõe eliminar, reduzir, elevar e criar atributos.','Uma oferta elimina complexidades, reduz espera, eleva conveniência e cria uma nova experiência.','Quais são as quatro ações do Oceano Azul?','Eliminar, reduzir, elevar e criar','Planejar, fazer, checar e agir','Produto, preço, praça e promoção','Comprar, produzir, estocar e vender'],
 [2,'Kaizen','É melhoria contínua, com participação das pessoas e aperfeiçoamentos sucessivos dos processos.','A equipe avalia diariamente pequenas causas de atraso e testa melhorias.','Qual prática representa Kaizen?','Melhorias contínuas com participação da equipe','Mudar tudo uma única vez e parar de medir','Esperar apenas por grandes invenções','Manter problemas sem análise'],
 [3,'Planejamento da inovação','Alinha objetivos, oportunidades, recursos, prioridades, responsabilidades e avaliação de resultados.','Uma empresa prioriza projetos considerando problema, orçamento, prazo e impacto esperado.','Qual é uma função do planejamento da inovação?','Alinhar iniciativas aos objetivos e recursos disponíveis','Eliminar toda incerteza do futuro','Escolher projetos sem critérios','Garantir sucesso de qualquer ideia'],
 [3,'Modelo linear','Representa o processo como uma sequência de etapas, como pesquisa, desenvolvimento, produção e comercialização. É uma simplificação.','Uma representação mostra pesquisa seguida de desenvolvimento e lançamento.','Qual característica identifica o modelo linear?','Sequência de etapas em uma direção predominante','Feedbacks múltiplos como elemento central','Ausência de etapas','Rede de interações como única representação'],
 [3,'Modelo interativo','Enfatiza relações e feedbacks entre atividades, atores e conhecimentos ao longo da inovação.','O retorno dos clientes leva a rever projeto e produção.','Um processo que revê o projeto após feedback do mercado é:','Interativo','Linear sem retorno','Isolado do mercado','Incompatível com aprendizagem'],
 [3,'Indicadores de inovação','Indicadores podem medir entradas, processos, saídas e resultados. Investimento em P&D não comprova sozinho valor gerado.','A empresa acompanha gasto em pesquisa, tempo de desenvolvimento e adoção da solução.','Por que combinar diferentes indicadores?','Para relacionar recursos, execução e resultados','Porque gasto em pesquisa garante sucesso','Para substituir objetivos por números aleatórios','Porque patentes medem todo impacto possível'],
 [3,'Innovation Scorecard','Organiza indicadores ligados à estratégia de inovação em diferentes dimensões. Deve equilibrar recursos, processos e resultados conforme o modelo adotado.','Um painel relaciona capacidades, projetos e resultados esperados.','Qual é o papel de um Innovation Scorecard?','Acompanhar a inovação por indicadores alinhados à estratégia','Contar apenas ideias sem avaliar execução','Garantir inovação sem recursos','Substituir análise por um único número universal'],
 [3,'Políticas públicas e FNDCT','Políticas públicas podem apoiar ciência, tecnologia e inovação. O FNDCT é o Fundo Nacional de Desenvolvimento Científico e Tecnológico.','Um projeto busca apoio a pesquisa e desenvolvimento em instrumentos públicos.','Qual é a finalidade geral do FNDCT?','Apoiar o desenvolvimento científico e tecnológico','Financiar exclusivamente propaganda comercial','Substituir todas as universidades','Eliminar a necessidade de avaliar projetos'],
 [3,'Pesquisa e desenvolvimento','P&D envolve trabalho sistemático para ampliar conhecimentos e utilizá-los em novas aplicações. Nem toda atividade inovadora é P&D.','Uma equipe investiga uma solução técnica e testa seu desenvolvimento.','Qual afirmação sobre P&D é adequada?','É uma atividade relevante, mas não esgota todas as atividades de inovação','Toda mudança de preço é P&D','Toda inovação exige laboratório próprio','P&D e publicidade são equivalentes'],
 [3,'Difusão da inovação','É a disseminação e adoção de uma inovação entre usuários, organizações ou mercados ao longo do tempo.','Outras operações passam a adotar um método já introduzido por uma empresa.','O que representa difusão?','Disseminação e adoção de uma inovação','Apenas a invenção inicial','Proteção total contra qualquer adoção','Interrupção obrigatória do uso'],
 [3,'Sistema Nacional de Inovação','O SNI envolve instituições e relações entre empresas, universidades, governo e outros atores que produzem e difundem conhecimento.','Universidade, empresa e agência pública colaboram em um projeto.','O SNI é melhor entendido como:','Um conjunto de instituições e interações para inovação','Um laboratório isolado','Uma única empresa que concentra toda pesquisa','Somente a legislação tributária'],
 [3,'Fontes de Drucker','As sete fontes incluem inesperado, incongruências, necessidades de processo, mudanças na indústria ou mercado, demografia, percepção e novos conhecimentos.','Uma falha recorrente no fluxo revela uma necessidade de processo.','Uma dificuldade persistente numa rotina pode revelar qual fonte de oportunidade?','Necessidade de processo','Somente mudança demográfica','Obrigatoriamente novo conhecimento científico','Ausência de oportunidade'],
 [3,'Gestão da mudança','Envolve comunicação, participação, capacitação e acompanhamento para incorporar novas práticas. Resistência precisa ser compreendida.','Antes de mudar o sistema de pedidos, a empresa treina a equipe e acompanha dificuldades.','Qual ação favorece a adoção de uma mudança?','Comunicar, capacitar e acompanhar a equipe','Impor a mudança sem explicar objetivos','Ignorar dificuldades operacionais','Tratar toda resistência como má vontade'],
 [4,'Recursos organizacionais','São ativos e capacidades mobilizados pela organização. Recursos isolados não garantem vantagem: importa como são combinados e utilizados.','Equipamentos, marca, conhecimento e rotinas sustentam a operação.','Qual afirmação sobre recursos é adequada?','Seu uso e combinação influenciam a capacidade de competir','Qualquer recurso gera vantagem automaticamente','Somente dinheiro é recurso','Recursos humanos não afetam resultados'],
 [4,'Tangíveis e intangíveis','Tangíveis têm expressão material, como instalações e equipamentos. Intangíveis incluem marca, conhecimento, reputação e relações.','O forno é tangível; a reputação do restaurante é intangível.','Qual recurso é intangível?','Reputação da empresa','Prédio da cozinha','Veículo de entrega','Equipamento de cocção'],
 [4,'Capital intelectual','Abrange conhecimentos e ativos intangíveis associados às pessoas, estruturas e relações da organização.','Conhecimento da equipe, processos documentados e relações com clientes compõem esse capital.','Qual conjunto representa dimensões usuais do capital intelectual?','Capital humano, estrutural e relacional','Apenas caixa, estoque e imóveis','Somente máquinas e veículos','Apenas a quantidade de funcionários'],
 [4,'Capital humano','Compreende conhecimentos, habilidades e experiências das pessoas. Desenvolvê-lo envolve aprendizagem e condições para aplicar competências.','Uma equipe aprende a analisar perdas e ajustar o processo.','Como desenvolver capital humano?','Capacitar pessoas e favorecer aplicação do conhecimento','Comprar equipamentos sem treinar ninguém','Contar apenas o número de empregados','Excluir a experiência prática da aprendizagem'],
 [4,'Competências essenciais','São capacidades coletivas que combinam conhecimentos e recursos, geram valor ao cliente e são difíceis de imitar.','A integração entre compras, cozinha e atendimento sustenta uma entrega consistentemente superior.','Qual característica favorece uma competência essencial?','Combinação difícil de imitar que gera valor ao cliente','Uma tarefa comum sem valor percebido','Um equipamento disponível igualmente a todos, isoladamente','Qualquer atividade apenas por existir'],
 [4,'Tecnologia e capacidades','A tecnologia gera resultados quando integrada a competências, processos e objetivos. Comprar um sistema não garante melhor desempenho.','Um sistema de estoque exige dados confiáveis e rotinas de registro.','Por que a compra de tecnologia pode não gerar vantagem?','Porque depende de integração com pessoas e processos','Porque tecnologia nunca agrega valor','Porque treinamento é sempre desnecessário','Porque dados não influenciam sua utilização'],
 [4,'Vantagem competitiva sustentável','Relaciona-se a recursos e capacidades valiosos, raros, difíceis de imitar e bem explorados pela organização. Sustentável não significa eterna.','Rotinas e conhecimento acumulado dificultam a reprodução do desempenho por concorrentes.','Qual condição fortalece uma vantagem sustentável?','Capacidades valiosas e difíceis de imitar, apoiadas pela organização','Qualquer recurso facilmente copiável','Preço baixo sem sustentação de custos','Imobilidade diante das mudanças'],
 [4,'Modelo 7S','O modelo considera estratégia, estrutura, sistemas, valores compartilhados, habilidades, estilo e pessoas. Destaca o alinhamento entre esses elementos.','Uma nova estratégia requer ajustar rotinas, competências e estilo de liderança.','Qual conjunto pertence ao modelo 7S?','Estratégia, estrutura, sistemas, valores, habilidades, estilo e pessoas','Produto, preço, praça, promoção, prazo, lucro e estoque','Somente sete indicadores financeiros','Pesquisa, protótipo, patente, preço, praça, produto e promoção'],
];
const recovered = new Set(['Inovação aberta','Inovação fechada','Inovação incremental','Modelo linear','Modelo interativo','Chain-link','Marketing e organização']);
export const topics: Topic[] = rows.map((r,i)=>({id:`t${i+1}`,unit:r[0],title:r[1],academic:r[2],simple:lessons[`t${i+1}`].simple,deeper:lessons[`t${i+1}`].deeper,misconception:lessons[`t${i+1}`].misconception,example:r[3],verified:recovered.has(r[1]),source:recovered.has(r[1])?'Conversa Estudo Unidade 1 Inovação — explicação recuperada; ampliação editorial com exemplos fictícios':'Síntese editorial do escopo solicitado — conferir com a apostila'}));
const baseQuestions: Question[] = rows.map((r,i)=>{
 const correct=i%4; const options=r.slice(5) as string[]; const answer=options.shift()!; options.splice(correct,0,answer);
 return {id:`q${i+1}`,topicId:`t${i+1}`,unit:r[0],prompt:r[4],options,correct,explanations:options.map((o,j)=>j===correct?`Correta. ${r[2]}`:`“${o}” não corresponde ao conceito. ${r[2]}`),source:topics[i].source};
});
function variant(t:Topic,suffix:string,prompt:string,choices:[string,string][],position:number):Question{
 const ordered=[...choices];const right=ordered.shift()!;ordered.splice(position,0,right);
 return {id:`${t.id}-${suffix}`,topicId:t.id,unit:t.unit,prompt,options:ordered.map(c=>c[0]),correct:position,explanations:ordered.map(c=>c[1]),source:t.source};
}
export const questions:Question[]=[...baseQuestions,...topics.flatMap((t,i)=>{
 const l=lessons[t.id];return [
  variant(t,'caso',l.casePrompt,l.choices,(i+1)%4),
  variant(t,'revisao',`Ao revisar ${t.title}, qual afirmação precisa ser corrigida?`,[
   [l.misconception,`Esta é a afirmação que precisa ser corrigida. ${l.simple} ${l.deeper}`],
   [l.simple,'Esta afirmação está de acordo com a síntese. A pergunta pede identificar a afirmação que precisa de correção.'],
   [t.academic,'Esta afirmação corresponde ao conceito apresentado. Procure a ideia que contradiz a explicação.'],
   [l.deeper,'Este comentário é compatível com o ensinamento. A afirmação equivocada é outra.'],
  ],(i+2)%4),
 ];
})];
