import {test,expect} from '@playwright/test';
async function nav(page:import('@playwright/test').Page,label:string){const menu=page.getByRole('button',{name:'Abrir menu'});if(await menu.isVisible())await menu.click();await page.getByRole('button',{name:label,exact:true}).click()}
test('dashboard, learn, tutor, persistence, errors, quick review and editor',async({page},info)=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:'Vamos avançar?'})).toBeVisible();await page.screenshot({path:`test-results/${info.project.name}-dashboard.png`,fullPage:true});
 await page.getByRole('button',{name:'Começar a aprender'}).click();await expect(page.getByRole('heading',{name:'O conceito',exact:true})).toBeVisible();await expect(page.locator('.option')).toHaveCount(0);await page.getByRole('button',{name:'Vamos praticar',exact:true}).click();await expect(page.getByRole('button',{name:'Professor, não entendi',exact:true})).toBeDisabled();await page.locator('.option').first().click();await expect(page.locator('.feedback')).toBeVisible();await page.getByRole('button',{name:'Professor, não entendi',exact:true}).click();await expect(page.getByText('Explicação local · sem IA',{exact:true})).toBeVisible();await page.screenshot({path:`test-results/${info.project.name}-question.png`,fullPage:true});
 await page.reload();await expect(page.locator('.feedback')).toBeVisible();await page.getByRole('button',{name:'Visão geral',exact:true}).last().click();await page.getByRole('button',{name:/Revisão Rápida Relembre/}).click();await expect(page.getByRole('button',{name:'Próximo conceito'})).toBeVisible();
 await nav(page,'Banco de questões');await page.getByRole('button',{name:'Nova questão',exact:true}).click();await page.getByLabel('Enunciado',{exact:true}).fill('Qual prática representa a implementação de uma inovação?');for(let i=0;i<4;i++){await page.getByLabel(`Alternativa ${'ABCD'[i]}`,{exact:true}).fill(['Aplicar uma solução','Apenas imaginar','Apenas anotar','Não executar'][i]);await page.getByLabel(`Explicação ${'ABCD'[i]}`,{exact:true}).fill('A inovação exige implementação, além da ideia.')}await page.getByLabel('Fonte / trecho de evidência').fill('Síntese editorial do conceito de inovação.');await page.getByRole('button',{name:'Salvar questão'}).click();await page.getByRole('textbox',{name:'Buscar questão'}).fill('Qual prática representa a implementação');await expect(page.locator('.bank-row')).toHaveCount(1);await page.reload();await page.getByRole('button',{name:'Fechar aviso'}).count();await nav(page,'Banco de questões');await page.getByRole('textbox',{name:'Buscar questão'}).fill('Qual prática representa a implementação');await expect(page.locator('.bank-row')).toHaveCount(1);
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);expect(overflow).toBe(false);
});
test('exam hides tutor and feedback then produces saved report',async({page},info)=>{await page.goto('/');await page.getByRole('button',{name:/Simulado Teste sem/}).click();for(let i=0;i<10;i++){await page.locator('.option').first().click();await expect(page.locator('.feedback')).toHaveCount(0);await expect(page.getByRole('button',{name:'Professor, não entendi'})).toHaveCount(0);await page.getByRole('button',{name:i===9?'Ver resultado':'Próxima',exact:true}).click()}await expect(page.getByRole('heading',{name:'Correção completa'})).toBeVisible();await expect(page.locator('.result-answer')).toHaveCount(10);await page.screenshot({path:`test-results/${info.project.name}-report.png`,fullPage:true});await nav(page,'Histórico');await expect(page.getByRole('heading',{name:'Sessões concluídas'})).toBeVisible();await expect(page.locator('button.history-row')).toHaveCount(1)});
test('AI without credentials returns an honest unavailable message',async({request})=>{const r=await request.post('/api/ai',{data:{action:'generate',topicId:'t1'}});if(process.env.TEST_STATIC==='1'){expect(r.status()).toBe(404)}else{expect(r.status()).toBe(503);expect((await r.json()).error).toContain('IA paga desativada')}});
test('offline first visit caches application and preserves answers',async({page,context})=>{await page.goto('/');await page.evaluate(async()=>{await navigator.serviceWorker.ready});await expect.poll(async()=>page.evaluate(async()=>{const cache=await caches.open('trilha-v7');return (await cache.keys()).filter(r=>r.url.includes('/_next/static/')).length})).toBeGreaterThan(0);await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{name:'Vamos avançar?'})).toBeVisible();await page.getByRole('button',{name:/Praticar Reforce/}).click();await page.locator('.option').first().click();await expect(page.locator('.feedback')).toBeVisible();await page.reload();await expect(page.locator('.feedback')).toBeVisible();await context.setOffline(false)});
test('wrong response appears in errors and clears after successful review',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/Praticar Reforce/}).click();const correct=await page.evaluate(()=>JSON.parse(localStorage.getItem('trilha:v1:guest')!).current.questions[0].correct as number);await page.locator('.option').nth((correct+1)%4).click();const menu=page.getByRole('button',{name:'Abrir menu'});if(await menu.isVisible())await menu.click();await page.getByRole('button',{name:/^Meus erros/}).click();await expect(page.locator('.error-card')).toHaveCount(1);page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Revisar meus erros'}).click();await page.locator('.option').nth(correct).click();await page.getByRole('button',{name:'Ver resultado'}).click();if(await menu.isVisible())await menu.click();await page.getByRole('button',{name:'Meus erros',exact:true}).click();await expect(page.getByRole('heading',{name:'Nenhum erro pendente'})).toBeVisible()});
test('expanded lesson and three same-topic questions work offline without API calls',async({page,context},info)=>{
 const calls:string[]=[];page.on('request',r=>{if(r.url().includes('/api/ai'))calls.push(r.url())});
 await page.goto('/');await page.evaluate(async()=>{await navigator.serviceWorker.ready});await context.setOffline(true);
 await page.getByRole('button',{name:'Começar a aprender'}).click();await expect(page.getByRole('heading',{name:'Em palavras simples',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Entenda um pouco mais',exact:true})).toBeVisible();await page.screenshot({path:`test-results/${info.project.name}-lesson-offline.png`,fullPage:true});
 const read=()=>page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('trilha:v1:guest')!).current;return {id:s.questions[s.index].id,topic:s.questions[s.index].topicId,index:s.index,length:s.questions.length}});
 const first=await read();const ids=new Set([first.id]);
 for(let i=0;i<3;i++){
  await page.getByRole('button',{name:'Vamos praticar',exact:true}).click();await page.locator('.option').first().click();await page.getByRole('button',{name:'Professor, não entendi',exact:true}).click();
  await page.getByText('Quero entender melhor',{exact:true}).click();await expect(page.locator('.local-help').first().locator('p')).toBeVisible();
  await page.getByText('Qual confusão devo evitar?',{exact:true}).click();await expect(page.getByText('Ideia equivocada:',{exact:true})).toBeVisible();
  await page.getByText('Quero tirar uma dúvida no ChatGPT',{exact:true}).click();await expect(page.getByRole('textbox',{name:'Contexto para tirar dúvida'})).toHaveValue(/Minha dúvida é:/);
  await page.getByRole('button',{name:'Faça outra pergunta parecida',exact:true}).click();
  const state=await read();expect(state.topic).toBe(first.topic);if(i<2){expect(state.index).toBe(i+1);expect(ids.has(state.id)).toBe(false);ids.add(state.id)}else await expect(page.getByRole('status')).toContainText('já respondeu às questões');
 }
 expect(ids.size).toBe(3);expect(calls).toHaveLength(0);await page.reload();await expect(page.locator('.feedback')).toBeVisible();expect((await read()).index).toBe(2);await context.setOffline(false);
});
